# NumPy Arrays

One of the most important package for numerical and scientific computations.

One of the most importan package for DS/ ML/ AI.

### Python objects:

1. high-level number objects: integers, floating point
2. Containers: lists(costless insertion and append), dictionaries(fast lookup)

### Numpy Provides:

1. extension package to Python for multi-dimensional arrays.
2. closer to hardware(efficiency)
3. designed for scientific computation(convenience)
4. Also known as array oriented computing

In [1]:
import numpy as np
a= np.array([0,1,2,3])
print(a)

print(np.arange(10))

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


#### Why it is useful: 
Memory-efficient container that provides fast numerical operations.

In [2]:
#python Lists
L= range(1000)
%timeit [i**2 for i in L]

588 µs ± 66.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [3]:
a = np.arange(1000)
%timeit a**2

2.03 µs ± 112 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# Creating Arrays

#### 1.1 Manual Construction of arrays

In [4]:
#1-D

a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [5]:
#print dimensions

a.ndim

1

In [6]:
#shape

a.shape

(4,)

In [7]:
len(a)

4

In [8]:
#2-D, 3-D.....

b = np.array([[0,1,2],[3,4,5]])

b

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
b.ndim

2

In [10]:
b.shape

(2, 3)

In [11]:
len(b) #returns the size of the first dimension

2

In [12]:
c = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [13]:
c.ndim

3

In [14]:
c.shape

(2, 2, 2)

1. 1D arrays are called Vectors
2. 2D arrays are called Matrix
3. nD arrays are called Tensor

#### 1.2 Functions for creating arrays

In [15]:
#Using arrange function

#arange is an array-valued version of the built-in Python range function

a= np.arange(10) #0......n-1
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
b = np.arange(1,10,2) #start, end(eclusion), step
b

array([1, 3, 5, 7, 9])

In [17]:
#using linspace
#linear space

a= np.linspace(0,1,6) #start, end, number of points
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [18]:
#common arrays

a =np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
a =np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
#Identity Matrix= I 3x3
np.eye(3) #Return a 2-D array with ones on the diagonal and zeroes elsewhere

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [22]:
#create array using diag function
a = np.diag([1,2,3,4]) #construct a diagonal array.
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [23]:
np.diag(a) #Extract diagonal

array([1, 2, 3, 4])

In [24]:
#create array using random

#Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).
a = np.random.rand(4)
a

array([0.66481096, 0.57659804, 0.83113749, 0.0437394 ])

In [25]:
a=np.random.randn(4) #Return a sample (or samples) from the “standard normal” distribution.  ***Gausian***
a

array([1.00478393, 0.11972522, 0.40516238, 2.74692195])

#### Note:

For random samples from N(\mu, \sigma^2), use:

sigma * np.random.randn(...) + mu

# 2. Basic DataTypes

You may have noticed that, in some instances, array elements are displayed with a trailling dot (e.g. 2 vs 2). Tjis is due to difference in the data-type used:

In [26]:
a = np.arange(10)
a.dtype

dtype('int32')

In [34]:
#You can explicitly specify which data-type you want:

a = np.arange(10, dtype = 'float64')
a.dtype

dtype('float64')

In [35]:
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [38]:
#The default data type is float for zeroes and ones function

a =np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
a.dtype

dtype('float64')

#### other datatypes

In [41]:
d = np.array([1+2j, 2+4j]) #complex datatype
print(d.dtype)

complex128


In [43]:
b = np.array([True, False, False, True]) #Boolean datatype
print(b.dtype)

bool


In [45]:
s = np.array(['Ram', 'Robert', 'Rahim']) #String datatype
s.dtype

dtype('<U6')

In [46]:
print(s)

['Ram' 'Robert' 'Rahim']


**Each built-in data type has a character code that uniquely identifies it.**

'b' − boolean

'i' − (signed) integer

'u' − unsigned integer

'f' − floating-point

'c' − complex-floating point

'm' − timedelta

'M' − datetime

'O' − (Python) objects

'S', 'a' − (byte-)string

'U' − Unicode

'V' − raw data (void)

# 3.Indexing and Slicing

**3.1 Indexing**

The items of an array can be accessedd and assigned to the same way as other **Python sequences (e.g. lists)**:

In [48]:
a = np.arange(10)
print(a[5]) #indices begin at 0, like other Python sequences (and C/C++)

5


In [50]:
#For multidimensional arrays, indexes are tuple of integers:
a= np.diag([1,2,3])

In [52]:
print(a[2,2])

3


In [53]:
a[2,1] = 5 #assigning value

In [54]:
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

**3.2 SLicing**

In [56]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
a[1:8:2] #[startindex: endindex(exclusive): step]

array([1, 3, 5, 7])

In [59]:
# We can also combine assignment and slicing:
a= np.arange(10)
a[5:]= 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [60]:
b = np.arange(5)
a[5:] = b[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

# 4. Copies and Views

A slicing operation creates a view on the orignal array which is just a way of accessing array data. Thus the orignal array is not copied in memory. You can use **np.may_share_memory()** to check if two arrays share the same memory block.

**When modifying the view, the orignal array is modified as well:**

In [61]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
b =a [::2]
b

array([0, 2, 4, 6, 8])

In [65]:
np.shares_memory(a,b)

True

In [66]:
np.may_share_memory(a,b)

True

In [67]:
b[0] = 10
b

array([10,  2,  4,  6,  8])

In [68]:
a #eventhough we modified b, it update 'a' because both shares the same memory

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [71]:
a = np.arange(10)
c = a[::2].copy() #force a copy
c

[0 1 2 3 4 5 6 7 8 9]


In [72]:
np.may_share_memory(a,c)

False

In [73]:
c[0] = 10
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 5. Fancy Indexinng

NumPy arrays can be indexed with slice, but also with boolean or integer arrays **(masks)**. This method is called **fancy indexing**. It creates copies not views.

#### Using Boolean Mask

In [74]:
a = np.random.randint(0,20,15)
a

array([ 8,  4, 15, 16, 16,  0,  5,  6, 17,  8,  5,  1,  2,  8,  1])

In [79]:
mask = (a%2 == 0)

In [80]:
extract_from_a = a[mask]
extract_from_a

array([ 8,  4, 16, 16,  0,  6,  8,  2,  8])

**Indexing with a mask can be very useful to assign a new value to a sub-array:**

In [81]:
a[mask] = -1
a

array([-1, -1, 15, -1, -1, -1,  5, -1, 17, -1,  5,  1, -1, -1,  1])

**Indexing with an array of integers**

In [82]:
a = np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [83]:
#Indexing can be done with an array of integers, where the same index is repeated several time:
a[[2,3,2,4,2]]

array([20, 30, 20, 40, 20])

In [84]:
#New value can be assigned
a[[9,7]] = -200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])