In [1]:
import numpy as np

# Elementwise Operations

**1. Basic Operations**

**with scalars**

In [4]:
a = np.array([1,2,3,4,]) #creating an array
a + 1

array([2, 3, 4, 5])

In [5]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

#### All airthemtic operates elementwise

In [12]:
b = np.ones(4) + 1
a-b

array([-1.,  0.,  1.,  2.])

In [13]:
a * b

array([2., 4., 6., 8.])

In [15]:
#Matrix multiplication
c= np.diag([1,2,3,4])

print(c*c)
print('*****************')
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
*****************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


### Comparisons

In [16]:
a = np.array([1,2,3,4])
b = np.array([5,2,2,4])
a==b

array([False,  True, False,  True])

In [17]:
a > b

array([False, False,  True, False])

In [18]:
#array-wise comparison
a = np.array([1,2,3,4])
b = np.array([5,2,2,4])
c = np.array([1,2,3,4])

np.array_equal(a,b)

False

In [19]:
np.array_equal(a,c)

True

### Logical Operations

In [20]:
a = np.array([1,1,0,0], dtype = bool)
b = np.array([1,0,1,0], dtype = bool)

np.logical_or(a,b)

array([ True,  True,  True, False])

In [21]:
np.logical_and(a,b)

array([ True, False, False, False])

#### Transcendental functions:

In [23]:
a = np.arange(5)

np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [24]:
np.log(a)

C:\Users\Saurabh Kumar\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [26]:
np.exp(a) #evaluates e^x for each element in a given input

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

#### Shape Mismatch

In [27]:
a = np.arange(4)
a+ np.array([1,2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

# Basic Reductions

#### Computing Sums

In [30]:
x = np.arange(1,5)
x

array([1, 2, 3, 4])

In [31]:
np.sum(x)

10

In [32]:
#sum by rows and b comlumns

x = np.array([[1,1],[2,2]])
x

array([[1, 1],
       [2, 2]])

In [33]:
x.sum(axis=0) #column first dimension
# axis = 0 will sum the elements column wise

array([3, 3])

In [34]:
x.sum(axis=1) #rows second dimension
# axis = 1 will sum the elements row wise

array([2, 4])

#### Other reductions

In [35]:
x = np.array([1,3,2])
x.min()

1

In [36]:
x.max()

3

In [37]:
x.argmin() #index of minimum element

0

In [39]:
x.argmax() #index of maximum element

1

#### Logical Operations

In [40]:
np.all([True, True, False])

False

In [41]:
np.any([True, True, False])

True

In [42]:
#Note: can be used for array comparisons
a = np.zeros((50,50))
np.any(a != 0)

False

In [43]:
np.all(a==a)

True

In [44]:
a = np.array([1,2,3,2])
b = np.array([2,2,3,2])
c = np.array([7,10,6,8])
((a <= b) & (b <=c)).all()

True

#### Statistics

In [45]:
x= np.array([1,2,3,1])
y= np.array([[1,2,3],[5,6,1]])
x.mean()

1.75

In [47]:
np.median(x)

1.5

In [49]:
np.median(y, axis = -1) #last axis
# axis = -1 or 1 means the operation will be row wise

array([2., 5.])

In [51]:
x.std() #full population standard dev.

0.82915619758885

#### Example:

Data in population.txt describes the population of hares and lynxes(and carrots) in northern Canada during 20 years.

In [53]:
#load data into numpy array object
data = np.loadtxt('populations.txt')

In [54]:
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [55]:
year, hares, lynxes, carrots = data.T #columns to variables
print(year)

[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]


In [56]:
# The mean population over time
populations = data[:, 1:]
populations

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [58]:
#sample standard deviations
populations.std(axis=0)

array([20897.90645809, 16254.59153691,  3322.50622558])

In [59]:
#which species has the highest population each year?

np.argmax(populations, axis = 1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2],
      dtype=int64)

# Broadcasting

Basic operations on numpy arrays(addition, etc.) are elementwise.

This works on arrays of the same size. Neverheless, Its alsopossible to do operations on arrays of different sizes if NumPy can transfor these arrays so that they all have the same size: this conversion is called broadcasting.

In [61]:
a = np.tile(np.arange(0,40,10),(3,1))
print(a)
print('********************')
a=a.T
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
********************
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [62]:
b = np.array([0,1,2])

In [64]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [65]:
a= np.arange(0,40,10)
a.shape

(4,)

In [66]:
print(a)

[ 0 10 20 30]


In [67]:
a = a[:,np.newaxis] #adds a new axis -> 2D array
a.shape

(4, 1)

In [68]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [69]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

# Array Shape Manipulation

#### Flattening

In [70]:
a = np.array([[1,2,3],[4,5,6]])
a.ravel() #Return a continuous flattened array. A 1-D array, containing the elements of the input, is returned. A copy is made only if needed.

array([1, 2, 3, 4, 5, 6])

In [71]:
a.T #Transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [72]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

#### Reshaping

The inverse operation of flattening:

In [74]:
print(a.shape)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [76]:
b = a.ravel()
print(b)

[1 2 3 4 5 6]


In [77]:
b = b.reshape((2,3))
b

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
b[0,0] = 100
a

array([[100,   2,   3],
       [  4,   5,   6]])

#### Note and Beware: reshape may also return a Copy and not View!

In [85]:
a = np.zeros((3,2))
b = a.T.reshape(3*2)

In [86]:
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [87]:
b

array([0., 0., 0., 0., 0., 0.])

In [88]:
b[0] = 50

In [89]:
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [90]:
b

array([50.,  0.,  0.,  0.,  0.,  0.])

## Adding Dimensions

Indexing with the np.newaxis object allows us to add an axis to an array.

newaxis is used ro increase the dimensions of the existing array by one more dimension, when used once. Thus,

1D array will become 2D array

2D array will become 3D array and so on

In [91]:
z = np.array([1,2,3])
z

array([1, 2, 3])

In [93]:
z[:,np.newaxis]

array([[1],
       [2],
       [3]])

#### Dimension Shuffling

In [94]:
a = np.arange(4*3*2).reshape(4, 3, 2)
a.shape

(4, 3, 2)

In [95]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [98]:
a[0,2,1] #[Matrix Number, Row Num in the Matrix, Col Num in the Matrix]

5

#### Resizing

In [104]:
a = np.arange(4)
a.resize((8,))
a

array([0, 1, 2, 3, 0, 0, 0, 0])

However, it must not be referred to somewhere else:

In [106]:
b = a
a.resize((4,))

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

#### Sorting Data

In [107]:
#Sorting along an axis:
a = np.array([[5,4,6],[2,3,2]])
b = np.sort(a, axis=1)
b

array([[4, 5, 6],
       [2, 2, 3]])

In [108]:
#in-place sort
a.sort(axis=1)
a

array([[4, 5, 6],
       [2, 2, 3]])

In [109]:
#sorting with fancy indexing
a = np.array([4,3,1,2])
j = np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)

In [110]:
a[j]

array([1, 2, 3, 4])